services:
  - type: web
    name: dropmail-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app -c gunicorn_config.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8132711759:AAHUIrEfsDo0bID_4LKBr9x9qIYyUcPk3lQ
    healthCheckPath: /health
    autoDeploy: true 